---
title: "Assignment 3"
author: "Andrew Olson"
date: "September 26, 2018"
output: html_document
---

```{r setup, include=FALSE}
#Loading required libraries
require(rgdal)
require(leaflet)
require(leaflet.extras)

require(dplyr)
require(readxl)
require(stringr)

```



```{r echo=TRUE, include=FALSE}
#Loading Data
# loading spatial data
pacnty.load <- readOGR("./PA_Counties_clip/PA_Counties_clip.shp", layer = "PA_Counties_clip", GDAL1_integer64_policy = TRUE)

# loading economic data
econ.load <- read.csv("./aff_download/ACS_16_5YR_S1903_with_ann.csv")

# loading rail line data
rail <- readOGR("PaRailLines2018_07.geojson")

# loading school location data
school <- read_excel("Urban Centric and Metro Centric Locale Codes.xls")%>%
  #fixing lat & lon so it comes up as numbers
  mutate(Longitude = as.numeric(as.character(Longitude)), Latitude = as.numeric(as.character(Latitude)))

# merging spatial & econ data
pacnty <- pacnty.load[pacnty.load$NAME %in% econ.load$County,]
pacnty@data <- merge(pacnty@data, econ.load, sort = FALSE, by.x = "NAME", by.y = "County")
```

##Economic Status in PA

```{r}
#palette defined
pal <- colorNumeric(
  palette = "Blues",
  domain = pacnty$Median_Income)

#leaflet plot with PA median income colored
leaflet(data = pacnty) %>%
  addProviderTiles("Esri.WorldTopoMap", options = providerTileOptions(noWrap = TRUE)) %>%
  # The lights on this are hard to tell given the basemap, you might have benefited from a darker basemap, or a different palette color
  addPolygons(color = ~pal(`Median_Income`), popup = ~paste0("<b>", NAME, ":</b> $", format(Median_Income, big.mark = ","))) %>%
  addLegend(position = "topright", pal = pal, values = pacnty$Median_Income, title = "Median Income by County (dollars)")
  
```

## Rail Lines in PA

```{r}
#leaflet plot with Rail Lines
leaflet(data = rail) %>%
  addProviderTiles("Stamen.Toner", options = providerTileOptions(noWrap = TRUE)) %>%
  # Like this one!
  addPolylines(color = "#a8ddb5")
```

##Schools in PA

```{r}
#leaflet plot with clustered school locations
leaflet(data = school) %>%
  addProviderTiles("Stamen.Terrain") %>%
  addCircleMarkers(lng = ~Longitude, lat = ~Latitude, radius = 1.5, clusterOptions = markerClusterOptions())
```
